// Storage: one folder per meeting under userData/meetings/<id>/.
// Files: meta.json, audio.webm, transcript.json, levels.json, summaries.json
// and one protocol-<mall>.md per generated summary.
// The folder listing is the index — no database.

import { app } from 'electron'
import { join } from 'path'
import {
  mkdirSync,
  existsSync,
  readFileSync,
  writeFileSync,
  renameSync,
  rmSync,
  readdirSync,
  createWriteStream
} from 'fs'
import type { WriteStream } from 'fs'
import type { MeetingMeta, MeetingDetail, MeetingSummary, Transcript } from '../shared/types'
import type { LevelEnvelope } from '../shared/levels'
import { dismissSuggestionInTranscript, renameSpeakerInTranscript } from './diarize'
import { getDiarizationConfig } from './settings'
import { upsertProfile } from './speakerProfiles'

function meetingsDir(): string {
  const dir = join(app.getPath('userData'), 'meetings')
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
  return dir
}

// Meeting ids are generated by generateId() below; anything else coming over IPC
// is hostile (path traversal into rmSync/createWriteStream) and must be rejected.
const MEETING_ID_RE = /^[0-9]{14}-[a-z0-9]{1,12}$/

function assertValidId(id: string): void {
  if (!MEETING_ID_RE.test(id)) throw new Error(`Invalid meeting id: ${JSON.stringify(id)}`)
}

function meetingDir(id: string): string {
  assertValidId(id)
  return join(meetingsDir(), id)
}

function metaPath(id: string): string {
  return join(meetingDir(id), 'meta.json')
}

export function audioPath(id: string): string {
  return join(meetingDir(id), 'audio.webm')
}

/** Segment index 0 -> audio.webm (backward compatible), N>0 -> audio-N.webm. */
function segmentAudioPath(id: string, segmentIndex: number): string {
  const name = segmentIndex === 0 ? 'audio.webm' : `audio-${segmentIndex}.webm`
  return join(meetingDir(id), name)
}

/**
 * Audio segment files for a meeting, in play order. Existing single-file
 * recordings return [audio.webm]; rotated recordings return
 * [audio.webm, audio-1.webm, ...] up to the first missing index.
 */
export function audioSegmentPaths(id: string): string[] {
  const dir = meetingDir(id)
  const paths: string[] = []
  const base = join(dir, 'audio.webm')
  if (existsSync(base)) paths.push(base)
  for (let i = 1; ; i++) {
    const p = join(dir, `audio-${i}.webm`)
    if (!existsSync(p)) break
    paths.push(p)
  }
  return paths
}

function transcriptPath(id: string): string {
  return join(meetingDir(id), 'transcript.json')
}

function levelsPath(id: string): string {
  return join(meetingDir(id), 'levels.json')
}

/** Where 0.5 and earlier wrote the one and only protocol. */
const LEGACY_PROTOCOL_FILE = 'protocol.md'

function summaryIndexPath(id: string): string {
  return join(meetingDir(id), 'summaries.json')
}

/** Timestamp-based id with a short random suffix — sortable and collision-safe. */
function generateId(): string {
  const ts = new Date()
    .toISOString()
    .replace(/[-:.TZ]/g, '')
    .slice(0, 14)
  const rand = Math.random().toString(36).slice(2, 8)
  return `${ts}-${rand}`
}

export function readMeta(id: string): MeetingMeta | null {
  try {
    const raw = readFileSync(metaPath(id), 'utf-8')
    return JSON.parse(raw) as MeetingMeta
  } catch {
    return null
  }
}

export function writeMeta(meta: MeetingMeta): void {
  const dir = meetingDir(meta.id)
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
  // Atomic write: a crash mid-write must not truncate meta.json (which would
  // make the meeting vanish from the index). Write a temp file then rename.
  const target = metaPath(meta.id)
  const tmp = `${target}.tmp`
  writeFileSync(tmp, JSON.stringify(meta, null, 2), 'utf-8')
  renameSync(tmp, target)
}

/** Patch selected fields of a meeting's meta and persist. Returns the new meta. */
export function updateMeta(id: string, patch: Partial<MeetingMeta>): MeetingMeta | null {
  const current = readMeta(id)
  if (!current) return null
  const next: MeetingMeta = { ...current, ...patch }
  writeMeta(next)
  return next
}

/** Meetings currently being recorded (start -> finish/cancel). Drives hide-to-tray. */
const recordingIds = new Set<string>()

export function isRecordingActive(): boolean {
  return recordingIds.size > 0
}

export function createMeeting(title: string, templateId?: string): MeetingMeta {
  const id = generateId()
  const meta: MeetingMeta = {
    id,
    title: title.trim() || 'Nytt möte',
    createdAt: new Date().toISOString(),
    durationSec: 0,
    status: 'recording',
    ...(templateId ? { templateId } : {})
  }
  writeMeta(meta)
  recordingIds.add(id)
  return meta
}

export function listMeetings(): MeetingMeta[] {
  const dir = meetingsDir()
  let entries: string[]
  try {
    entries = readdirSync(dir, { withFileTypes: true })
      .filter((e) => e.isDirectory())
      .map((e) => e.name)
  } catch {
    return []
  }
  const metas: MeetingMeta[] = []
  for (const id of entries) {
    const meta = readMeta(id)
    if (meta) metas.push(meta)
  }
  // Newest first (ids and createdAt both sort chronologically).
  metas.sort((a, b) => (a.createdAt < b.createdAt ? 1 : a.createdAt > b.createdAt ? -1 : 0))
  return metas
}

export function readTranscript(id: string): Transcript | undefined {
  try {
    return JSON.parse(readFileSync(transcriptPath(id), 'utf-8')) as Transcript
  } catch {
    return undefined
  }
}

export function writeTranscript(id: string, transcript: Transcript): void {
  writeFileSync(transcriptPath(id), JSON.stringify(transcript, null, 2), 'utf-8')
}

export function hasTranscript(id: string): boolean {
  return existsSync(transcriptPath(id))
}

/**
 * Per-source level envelope from the recorder, used to tell the microphone
 * apart from the system audio. Written once when the recording finishes.
 */
export function readLevelEnvelope(id: string): LevelEnvelope | undefined {
  try {
    const parsed = JSON.parse(readFileSync(levelsPath(id), 'utf-8')) as Partial<LevelEnvelope>
    if (typeof parsed.rate !== 'number') return undefined
    if (!Array.isArray(parsed.mic) || !Array.isArray(parsed.system)) return undefined
    return { rate: parsed.rate, mic: parsed.mic, system: parsed.system }
  } catch {
    return undefined
  }
}

export function writeLevelEnvelope(id: string, envelope: LevelEnvelope): void {
  const dir = meetingDir(id)
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
  writeFileSync(levelsPath(id), JSON.stringify(envelope), 'utf-8')
}

/**
 * Set a diarized speaker's display name. No-op when transcript/speaker is
 * missing. A successful non-empty rename settles any recognition suggestion
 * for that speaker, and — with voice recognition enabled and an embedding on
 * the transcript — enrolls/updates the local voice profile for the name.
 */
export function renameSpeaker(id: string, speakerId: string, name: string): void {
  const transcript = readTranscript(id)
  if (!transcript) return
  let next = renameSpeakerInTranscript(transcript, speakerId, name)
  if (next === transcript) return

  const trimmed = name.trim()
  if (trimmed) {
    // The user has decided — whatever recognition suggested is now moot.
    next = dismissSuggestionInTranscript(next, speakerId)
    const embedding = next.speakerEmbeddings?.[speakerId]
    if (embedding && getDiarizationConfig().recognitionEnabled) {
      upsertProfile(trimmed, embedding)
    }
  }
  writeTranscript(id, next)
}

/** Reject a recognition suggestion. No-op when the suggestion is absent. */
export function dismissSpeakerSuggestion(id: string, speakerId: string): void {
  const transcript = readTranscript(id)
  if (!transcript) return
  const next = dismissSuggestionInTranscript(transcript, speakerId)
  if (next !== transcript) writeTranscript(id, next)
}

// ---- Summaries ----
//
// Each summary is its own markdown file named after the template it came from
// ('protocol-uppfoljningsmejl.md'), so the meeting folder stays readable from
// outside the app. summaries.json carries what the file name cannot: which
// template, what the user asked it to focus on, and when it was made.

/** What summaries.json holds — the summary minus its markdown. */
type SummaryEntry = Omit<MeetingSummary, 'markdown'>

/** Ascii, lowercase, hyphenated — safe as a file name on every platform. */
function slugify(input: string): string {
  const slug = input
    .toLowerCase()
    .replace(/[åä]/g, 'a')
    .replace(/ö/g, 'o')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
  return slug.slice(0, 40).replace(/-+$/, '')
}

/**
 * A readable, unique file name for a new summary: the template name, plus the
 * first words of the focus when there is one, so two summaries from the same
 * template stay apart. Falls back to a counter when that is still not enough.
 */
function summaryFileName(id: string, templateName: string, focus: string): string {
  const focusPart = focus ? slugify(focus).split('-').slice(0, 3).join('-') : ''
  const base = [slugify(templateName), focusPart].filter(Boolean).join('-') || 'sammanfattning'
  const taken = new Set(readSummaryIndex(id).map((e) => e.fileName))
  for (let n = 1; ; n++) {
    const name = n === 1 ? `protocol-${base}.md` : `protocol-${base}-${n}.md`
    if (!taken.has(name) && !existsSync(join(meetingDir(id), name))) return name
  }
}

function readSummaryIndex(id: string): SummaryEntry[] {
  try {
    const parsed = JSON.parse(readFileSync(summaryIndexPath(id), 'utf-8')) as unknown
    if (!Array.isArray(parsed)) return []
    // A hand-edited or truncated index must not take the meeting down with it.
    return parsed.filter(
      (e): e is SummaryEntry =>
        !!e &&
        typeof (e as SummaryEntry).id === 'string' &&
        typeof (e as SummaryEntry).fileName === 'string'
    )
  } catch {
    return []
  }
}

function writeSummaryIndex(id: string, entries: SummaryEntry[]): void {
  writeFileSync(summaryIndexPath(id), JSON.stringify(entries, null, 2), 'utf-8')
}

function readSummaryFile(id: string, fileName: string): string | undefined {
  try {
    return readFileSync(join(meetingDir(id), fileName), 'utf-8')
  } catch {
    return undefined
  }
}

/**
 * Every summary for a meeting, oldest first. A meeting recorded before
 * templates existed has a bare protocol.md and no index; it shows up as a
 * summary called 'Protokoll' so nothing recorded earlier disappears.
 */
export function listSummaries(id: string): MeetingSummary[] {
  const entries = readSummaryIndex(id)
  const summaries: MeetingSummary[] = []

  if (!entries.some((e) => e.fileName === LEGACY_PROTOCOL_FILE)) {
    const legacy = readSummaryFile(id, LEGACY_PROTOCOL_FILE)
    if (legacy !== undefined) {
      summaries.push({
        id: 'legacy',
        fileName: LEGACY_PROTOCOL_FILE,
        templateId: 'protokoll',
        templateName: 'Protokoll',
        focus: '',
        createdAt: readMeta(id)?.createdAt ?? new Date().toISOString(),
        markdown: legacy
      })
    }
  }

  for (const entry of entries) {
    const markdown = readSummaryFile(id, entry.fileName)
    // Skip entries whose file is gone rather than showing an empty summary.
    if (markdown === undefined) continue
    summaries.push({ ...entry, markdown })
  }
  return summaries
}

export function hasSummaries(id: string): boolean {
  return listSummaries(id).length > 0
}

/** Append a new summary and return it, markdown included. */
export function addSummary(
  id: string,
  summary: { templateId: string; templateName: string; focus: string; markdown: string }
): MeetingSummary {
  const dir = meetingDir(id)
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
  const entry: SummaryEntry = {
    id: `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`,
    fileName: summaryFileName(id, summary.templateName, summary.focus),
    templateId: summary.templateId,
    templateName: summary.templateName,
    focus: summary.focus,
    createdAt: new Date().toISOString()
  }
  writeFileSync(join(dir, entry.fileName), summary.markdown, 'utf-8')
  writeSummaryIndex(id, [...readSummaryIndex(id), entry])
  return { ...entry, markdown: summary.markdown }
}

/**
 * Overwrite an existing summary's markdown, keeping its file name and place in
 * the list — this is what a re-run after a speaker rename does. A legacy
 * protocol.md is upgraded to a real index entry on the way.
 */
export function updateSummaryMarkdown(id: string, summaryId: string, markdown: string): void {
  const existing = listSummaries(id).find((s) => s.id === summaryId)
  if (!existing) return
  writeFileSync(join(meetingDir(id), existing.fileName), markdown, 'utf-8')
  const entries = readSummaryIndex(id)
  if (entries.some((e) => e.id === summaryId)) return
  writeSummaryIndex(id, [
    {
      id: existing.id,
      fileName: existing.fileName,
      templateId: existing.templateId,
      templateName: existing.templateName,
      focus: existing.focus,
      createdAt: existing.createdAt
    },
    ...entries
  ])
}

/**
 * Remove one summary and its file. Deleting the last one is allowed — the
 * meeting keeps its transcript, and a new summary can be generated from any
 * template. A legacy protocol.md has no index entry to drop, only a file.
 */
export function deleteSummary(id: string, summaryId: string): void {
  const existing = listSummaries(id).find((s) => s.id === summaryId)
  if (!existing) return
  rmSync(join(meetingDir(id), existing.fileName), { force: true })
  writeSummaryIndex(
    id,
    readSummaryIndex(id).filter((e) => e.id !== summaryId)
  )
}

export function getMeeting(id: string): MeetingDetail | null {
  const meta = readMeta(id)
  if (!meta) return null
  return {
    ...meta,
    transcript: readTranscript(id),
    summaries: listSummaries(id)
  }
}

export function deleteMeeting(id: string): void {
  const dir = meetingDir(id)
  if (existsSync(dir)) rmSync(dir, { recursive: true, force: true })
}

export function renameMeeting(id: string, title: string): void {
  updateMeta(id, { title: title.trim() || 'Nytt möte' })
}

// ---- Recording: streamed audio append ----

// One WriteStream per (meeting id, segment index), keyed as `${id}#${segment}`.
const activeStreams = new Map<string, WriteStream>()
// Ids whose recording has been finalized or cancelled. A late chunk for such an
// id must be dropped — never reopen a stream (which would leak, or recreate a
// folder deleted by cancel).
const closedRecordings = new Set<string>()

function streamKey(id: string, segmentIndex: number): string {
  return `${id}#${segmentIndex}`
}

function assertValidSegmentIndex(segmentIndex: number): void {
  if (!Number.isInteger(segmentIndex) || segmentIndex < 0 || segmentIndex > 100000) {
    throw new Error(`Invalid segment index: ${JSON.stringify(segmentIndex)}`)
  }
}

function getStream(id: string, segmentIndex: number): WriteStream {
  const key = streamKey(id, segmentIndex)
  let stream = activeStreams.get(key)
  if (!stream) {
    const dir = meetingDir(id)
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
    // 'a' — append; chunks are streamed straight to disk, never buffered in memory.
    stream = createWriteStream(segmentAudioPath(id, segmentIndex), { flags: 'a' })
    activeStreams.set(key, stream)
  }
  return stream
}

export function appendAudioChunk(
  id: string,
  chunk: ArrayBuffer,
  segmentIndex: number = 0
): Promise<void> {
  const seg = segmentIndex ?? 0
  assertValidSegmentIndex(seg)
  // Drop chunks that arrive after finalize/cancel instead of resurrecting a stream.
  if (closedRecordings.has(id)) return Promise.resolve()
  return new Promise((resolve, reject) => {
    const stream = getStream(id, seg)
    stream.write(Buffer.from(chunk), (err) => (err ? reject(err) : resolve()))
  })
}

/** Close every open segment stream for a meeting. */
function closeStreams(id: string): Promise<void> {
  const prefix = `${id}#`
  const keys = [...activeStreams.keys()].filter((k) => k.startsWith(prefix))
  return Promise.all(
    keys.map((key) => {
      const stream = activeStreams.get(key)
      activeStreams.delete(key)
      if (!stream) return Promise.resolve()
      return new Promise<void>((resolve) => stream.end(() => resolve()))
    })
  ).then(() => undefined)
}

/** Close all audio streams and stamp duration + status 'recorded'. */
export async function finishRecording(id: string, durationSec: number): Promise<void> {
  // Mark closed first so any concurrently-arriving late chunk is dropped.
  closedRecordings.add(id)
  await closeStreams(id)
  recordingIds.delete(id)
  updateMeta(id, { durationSec: Math.max(0, Math.round(durationSec)), status: 'recorded' })
}

/** Close all audio streams and remove the whole folder. */
export async function cancelRecording(id: string): Promise<void> {
  closedRecordings.add(id)
  await closeStreams(id)
  recordingIds.delete(id)
  deleteMeeting(id)
}
