<#
.SYNOPSIS
  Generate the winget manifests for a published referat release.

.DESCRIPTION
  Installing through winget avoids the SmartScreen prompt entirely: the download
  never goes through the browser's reputation check. That matters more than a
  code signing certificate at this scale, and it costs nothing.

  The manifests reference a published release asset and carry its SHA256, so the
  release has to exist before this runs. Point -Version at it, review the output,
  then submit it to microsoft/winget-pkgs (see docs/winget.md).

.EXAMPLE
  ./scripts/winget-manifests.ps1 -Version 0.9.0
#>
param(
  # Defaults to the version in package.json.
  [string]$Version = '',
  [string]$OutDir = '',
  # Skip the download and hash a local file instead — useful before publishing.
  [string]$InstallerPath = ''
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot

if (-not $Version) {
  $Version = (Get-Content (Join-Path $root 'package.json') -Raw | ConvertFrom-Json).version
}
if (-not $OutDir) {
  $OutDir = Join-Path $root "dist\winget\$Version"
}

$identifier = 'Sockulags.Referat'
$installerUrl = "https://github.com/sockulags/referat/releases/download/v$Version/referat-setup.exe"
$manifestVersion = '1.6.0'

if ($InstallerPath) {
  if (-not (Test-Path -LiteralPath $InstallerPath)) { throw "No such installer: $InstallerPath" }
  $hashSource = $InstallerPath
  Write-Host "Hashing local installer: $InstallerPath"
} else {
  $hashSource = Join-Path ([IO.Path]::GetTempPath()) "referat-setup-$Version.exe"
  Write-Host "Downloading $installerUrl"
  Invoke-WebRequest -Uri $installerUrl -OutFile $hashSource -UseBasicParsing
}

$sha256 = (Get-FileHash -LiteralPath $hashSource -Algorithm SHA256).Hash.ToUpperInvariant()
if (-not $InstallerPath) { Remove-Item -LiteralPath $hashSource -Force }
Write-Host "SHA256: $sha256"

$releaseDate = (Get-Date).ToString('yyyy-MM-dd')
New-Item -ItemType Directory -Force -Path $OutDir | Out-Null

$header = @"
# Generated by scripts/winget-manifests.ps1 — do not hand-edit; regenerate instead.
# yaml-language-server: `$schema=https://aka.ms/winget-manifest.version.$manifestVersion.schema.json
"@

Set-Content -LiteralPath (Join-Path $OutDir "$identifier.yaml") -Encoding utf8 -Value @"
$header
PackageIdentifier: $identifier
PackageVersion: $Version
DefaultLocale: en-US
ManifestType: version
ManifestVersion: $manifestVersion
"@

Set-Content -LiteralPath (Join-Path $OutDir "$identifier.locale.en-US.yaml") -Encoding utf8 -Value @"
# Generated by scripts/winget-manifests.ps1 — do not hand-edit; regenerate instead.
# yaml-language-server: `$schema=https://aka.ms/winget-manifest.defaultLocale.$manifestVersion.schema.json
PackageIdentifier: $identifier
PackageVersion: $Version
PackageLocale: en-US
Publisher: Lucas Skog
PublisherUrl: https://github.com/sockulags
PublisherSupportUrl: https://github.com/sockulags/referat/issues
PackageName: referat
PackageUrl: https://github.com/sockulags/referat
License: MIT
LicenseUrl: https://github.com/sockulags/referat/blob/main/LICENSE
Copyright: Copyright (c) Lucas Skog
ShortDescription: Meeting notes that stay on your machine.
Description: |-
  referat records meetings on Windows, transcribes them and writes the minutes. You choose
  where the AI runs: on your own machine, on a server your IT department hosts, or at a cloud
  provider. Audio, transcripts and minutes are stored locally and nothing leaves the machine
  unless you configure an endpoint yourself.

  A meeting can be summarized through several templates - minutes, a quick recap, action items,
  a decision log or a follow-up email - and each summary can be narrowed to one part of the
  meeting. The transcript separates you from the other participants automatically when system
  audio is recorded; optional local speaker identification splits the others into individual
  voices.

  The interface is currently Swedish.
Moniker: referat
Tags:
- audio
- meeting
- meetings
- minutes
- privacy
- speech-to-text
- swedish
- transcription
ReleaseNotesUrl: https://github.com/sockulags/referat/releases/tag/v$Version
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/sockulags/referat/wiki
ManifestType: defaultLocale
ManifestVersion: $manifestVersion
"@

Set-Content -LiteralPath (Join-Path $OutDir "$identifier.installer.yaml") -Encoding utf8 -Value @"
# Generated by scripts/winget-manifests.ps1 — do not hand-edit; regenerate instead.
# yaml-language-server: `$schema=https://aka.ms/winget-manifest.installer.$manifestVersion.schema.json
PackageIdentifier: $identifier
PackageVersion: $Version
InstallerType: nullsoft
# electron-builder builds a one-click, per-user NSIS installer (perMachine: false).
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: $releaseDate
AppsAndFeaturesEntries:
- DisplayName: referat
  Publisher: Lucas Skog
  DisplayVersion: $Version
Installers:
- Architecture: x64
  InstallerUrl: $installerUrl
  InstallerSha256: $sha256
ManifestType: installer
ManifestVersion: $manifestVersion
"@

Write-Host ""
Write-Host "Manifests written to $OutDir"
Write-Host "Validate: winget validate --manifest `"$OutDir`""
Write-Host "Then submit them per docs/winget.md."
